"""link

Revision ID: 7c84607220e7
Revises: db79e5114753
Create Date: 2023-11-17 19:22:22.489958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c84607220e7'
down_revision = 'db79e5114753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.drop_column('website')

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
